version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/checkout
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout:
          path: ~/checkout

      - setup_remote_docker

      - run:
          name: Installing qemu
          command: |
            sudo apt-get install -y qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static:register
            sudo cp /usr/bin/qemu-arm-static ~/checkout

      - run:
          name: Build amd64
          command: |
            ./build_and_action.sh ./create_package.sh logfmt:build Dockerfile
            
      - run:
          name: Build arm
          command: |
            ./clean.sh
            ./build_and_action.sh ./arm_create_package.sh logfmt:build-arm Dockerfile.arm

      - run:
          name: Upload packages
          command: |
            ./build_and_action.sh ./upload_packages.sh logfmt:build Dockerfile

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: org-global
