version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/checkout
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout:
          path: ~/checkout

      - setup_remote_docker

      - run:
          name: Installing kin_ci
          command: |
            mkdir -p ~/.local/bin/ 
            curl https://s3-us-west-2.amazonaws.com/ci.kindredai.net/kin_ci/master/kin_ci > ~/.local/bin/kin_ci
            chmod +x ~/.local/bin/kin_ci

      - run:
          name: Installing qemu
          command: |
            sudo apt-get install -y qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static:register
            sudo cp /usr/bin/qemu-arm-static ~/checkout

      - run:
          name: Build and Deploy amd64
          command: |
            mkdir -p ./build
            ./build_and_action.sh ./create_package.sh
            
      - run:
          name: Build and Deploy arm
          command: |
            rm -rf ./build
            ./clean.sh
            mkdir -p ./build
            ./arm_build_and_action.sh ./arm_create_package.sh

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: org-global
