version: 2
jobs:
  run_tests:
    parallelism: 1
    working_directory: ~/checkout
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout:
          path: ~/checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Installing kin_ci
          command: |
            mkdir -p ~/.local/bin/ 
            curl https://s3-us-west-2.amazonaws.com/ci.kindredai.net/kin_ci/master/kin_ci > ~/.local/bin/kin_ci
            chmod +x ~/.local/bin/kin_ci

      - run:
          name: Build and Upload
          command: |
            mkdir -p ./build
            ./build_and_action.sh ./create_package.sh

workflows:
  version: 2
  all:
    jobs:
      - run_tests:
          context: org-global
